# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: 
  ru: 
# email: 
description:
  en: Sergey Dovgal's personal homepage
  ru: Личная страница Серёжи Довгаля
index:
  en: index.html
  ru: index_ru.html
feed:
  en: /feed.xml
  ru: /feed.xml
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: electric-tric

# Build settings
markdown: kramdown

home:
  en: "[home]"
  ru: "[в начало]"
